backend:
  name: git-gateway
  branch: master
media_folder: static/cms/images
public_folder: cms/images
collections:
  - name: "projects"
    label: "Projects"
    folder: "static/cms/projects"
    create: true
    identifier_field: "slug"
    fields:
      - label: "Slug"
        hint: "The piece of URL as in annacingi.com/projects/[THIS]"
        name: "slug"
        widget: "string"
        pattern: ['[a-z0-9\-]+$', "Lowercase letters, numbers and dashes only"]
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Opening Date"
        name: "openingDate"
        widget: "datetime"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Caption"
            name: "caption"
            widget: "string"
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["theatre", "opera"]
  - name: "sections"
    label: "Sections"
    files:
      - label: "About"
        name: "about"
        file: "static/cms/about.md"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "CV"
        name: "cv"
        file: "static/cms/cv.md"
        fields:
          - label: "CV Italian"
            name: "cvItalian"
            widget: "file"
          - label: "CV English"
            name: "cvEnglish"
            widget: "file"
