backend:
  name: git-gateway
  branch: master
media_folder: static/cms/images
public_folder: cms/images
collections:
  - name: "projects"
    label: "Projects"
    folder: "static/cms/projects"
    create: true
    identifier_field: "slug"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Location"
        name: "location"
        widget: "string"
      - label: "Opening Date"
        name: "openingDate"
        widget: "datetime"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["theatre", "opera"]
  - name: "sections"
    label: "Sections"
    files:
      - label: "About"
        name: "about"
        file: "static/cms/about.md"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "CV"
        name: "cv"
        file: "static/cms/cv.md"
        fields:
          - label: "CV Italian"
            name: "cvItalian"
            widget: "file"
          - label: "CV English"
            name: "cvEnglish"
            widget: "file"
